// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcaemoljtmtcwvibxomc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjYWVtb2xqdG10Y3d2aWJ4b21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwMTA1ODEsImV4cCI6MjEwMTU4NjU4MX0.CZJv4ywa1XSjppjfOfc3Cs-sqcvEPou3AF7BKcLA6NQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});